#!/usr/bin/env python3
# automates link degradation for batman nodes running
# inside Linux network namespaces

import re
import sys
import time
import subprocess
import csv
import os

# returns output generated by command
def run_cmd(cmd):
    print(f"[EXEC] {cmd}")

    # execute the command and capture output
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

    # report errors
    if result.returncode != 0 and "No such file or directory" not in result.stderr:
        print(f"[ERROR] {result.stderr.strip()}")
    
    return result.stdout.strip()

def apply_degradation(netns, interface, delay_ms=0, loss_pct=0, jitter_ms=0):
    # adds synthetic network degradation to simulate real network conditions
    # uses netns for degradation inside Linux network namespaces

    tc_args = []

    # construct latency and jitter
    if delay_ms > 0:
        if jitter_ms > 0:
            tc_args.append(f"delay {delay_ms}ms {jitter_ms}ms")
        else:
            tc_args.append(f"delay {delay_ms}ms")

    # construct packet loss
    if loss_pct > 0:
        tc_args.append(f"loss {loss_pct}%")

    # exit early if no parameters
    if not tc_args:
        print(f"[INFO] No degradation parameters specified for {interface}.")
        return

    # combine arguments into single payload
    params = " ".join(tc_args)

    # clear existing queuing discipline rules to avoid conflicts
    run_cmd(f"sudo ip netns exec {netns} tc qdisc del dev {interface} root 2>/dev/null")

    # attach new netem qdisc rule to root of interface
    run_cmd(f"sudo ip netns exec {netns} tc qdisc add dev {interface} root netem {params}")

    print(f"[SUCCESS] Applied tc netem ({params}) on {interface} in {netns}")

def clear_degredation(netns, interface):
    # clears any existing network degradation on the specified interface within the given network namespace
    run_cmd(f"sudo ip netns exec {netns} tc qdisc del dev {interface} root 2>/dev/null")
    print(f"[SUCCESS] Cleared degradation rules on {interface} in {netns}")

# Reads the transmit quality between the nodes
# Reads active route quality specifically for a target MAC or active destination
def read_active_quality(netns="vnode1", target_mac="7a:62:86:7e:cb:bb"):
    output = run_cmd(f"sudo ip netns exec {netns} batctl o")

    for line in output.split('\n'):
        # Match lines marked with '*' (active route)
        if line.strip().startswith("*"):
            # Ensure we are parsing the row for vnode2
            if target_mac and target_mac not in line:
                continue

            parts = line.split()
            tq_match = re.search(r"\((\d+)\)", line) 
            tq = int(tq_match.group(1)) if tq_match else None
            
            nexthop = parts[3] if len(parts) > 3 else "unknown"
            
            outgoing_if_match = re.search(r"\[\s*(\S+)\s*\]", line)
            outgoing_if = outgoing_if_match.group(1) if outgoing_if_match else "unknown"

            return tq, nexthop, outgoing_if

    return None, "None", "None"

def export_data(loss_levels=[10, 30, 50, 100]):
    # How long each phase lasts, in seconds (placeholders for testing)
    BASELINE_S = 30     # Time of clean link
    DEGRADE_S = 120     # Time loss is applied
    RECOVER_S = 180     # Time loss recovers   
    #LOSS_PCT = 30       # How much loss to apply
    total_s = BASELINE_S + DEGRADE_S + RECOVER_S    # Total time of experiment

    os.makedirs("TQ_EXPS", exist_ok=True)

    for loss_pct in loss_levels:
        filename = f"TQ_EXPS/TQ_EXP_loss{loss_pct}.csv"
        print(f"\n--- Starting TQ Experiment for {loss_pct}% Loss ---")

        curr_loss = 0   # Switch for applying loss later
        start = time.time() # When the start was
        
        with open(filename, "w", newline="") as file:
            # Write all data at once
            writer = csv.writer(file)
            writer.writerow(["time_s", "TQ", "loss_pct", "nexthop", "outgoing_if"])

            elapsed = 0 # Elapsed time of exp
            while elapsed < total_s:
                # Turn loss on when the baseline phase ends
                if elapsed >= BASELINE_S and curr_loss == 0 and elapsed < BASELINE_S + DEGRADE_S:
                    apply_degradation("vnode1", "veth1-2", loss_pct=loss_pct)
                    apply_degradation("vnode2", "veth2-1", loss_pct=loss_pct)
                    curr_loss = loss_pct

            # Turn loss off when the damage phase ends
                if elapsed >= BASELINE_S + DEGRADE_S and curr_loss != 0:
                    clear_degredation("vnode1", "veth1-2")
                    clear_degredation("vnode2", "veth2-1")
                    curr_loss = 0

                # Measure and record one row
                # Measure and record one row for vnode2's MAC
                tq, nexthop, outgoing_if = read_active_quality("vnode1", target_mac="7a:62:86:7e:cb:bb")
                writer.writerow([round(elapsed, 1), tq, curr_loss, nexthop, outgoing_if])
                file.flush() # Write lagging data

                # ADelay 1 second and update elapsed
                time.sleep(1)
                elapsed = time.time() - start

        print(f"[SUCCESS] Saved data to {filename}")
    
        
if __name__ == "__main__":
    # FOr exporting csv files for updating
    print("--- Starting TQ Experiment ---")
    export_data()
    print("--- All Experiments Complete ---")
    
    # print("--- Starting Mesh Link Degradation Test ---")

    # # configure targets
    # TARGET_NS = "vnode1"
    # TARGET_IF = "veth1-2"

    # # basic degradation
    # apply_degradation(netns=TARGET_NS, interface=TARGET_IF, delay_ms=100, jitter_ms=20, loss_pct=10)
    
    # print("[INFO] Testing active for 10 seconds...")
    # time.sleep(10)

    # # reset degradation back to baseline
    # clear_degredation(netns=TARGET_NS, interface=TARGET_IF)
    # print("--- Test Complete ---")

    # #print out the TQ for data collection
    # print("TQ is:", read_transmit_quality(TARGET_NS))