#!/usr/bin/env python3
# automates link degradation for batman nodes running
# inside Linux network namespaces

import sys
import time
import subprocess

# returns output generated by command
def run_cmd(cmd):
    print(f"[EXEC] {cmd}")

    # execute the command and capture output
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

    # report errors
    if result.returncode != 0 and "No such file or directory" not in result.stderr:
        print(f"[ERROR] {result.stderr.strip()}")
    
    return result.stdout.strip()

def apply_degradation(netns, interface, delay_ms=0, loss_pct=0, jitter_ms=0):
    # adds synthetic network degradation to simulate real network conditions
    # uses netns for degradation inside Linux network namespaces

    tc_args = []

    # construct latency and jitter
    if delay_ms > 0:
        if jitter_ms > 0:
            tc_args.append(f"delay {delay_ms}ms {jitter_ms}ms")
        else:
            tc_args.append(f"delay {delay_ms}ms")

    # construct packet loss
    if loss_pct > 0:
        tc_args.append(f"loss {loss_pct}%")

    # exit early if no parameters
    if not tc_args:
        print(f"[INFO] No degradation parameters specified for {interface}.")
        return

    # combine arguments into single payload
    params = " ".join(tc_args)

    # clear existing queuing discipline rules to avoid conflicts
    run_cmd(f"sudo ip netns exec {netns} tc qdisc del dev {interface} root 2>/dev/null")

    # attach new netem qdisc rule to root of interface
    run_cmd(f"sudo ip netns exec {netns} tc qdisc add dev {interface} root netem {params}")

    print(f"[SUCCESS] Applied tc netem ({params}) on {interface} in {netns}")

def clear_degredation(netns, interface):
    # clears any existing network degradation on the specified interface within the given network namespace
    run_cmd(f"sudo ip netns exec {netns} tc qdisc del dev {interface} root 2>/dev/null")
    print(f"[SUCCESS] Cleared degradation rules on {interface} in {netns}")

if __name__ == "__main__":
    print("--- Starting Mesh Link Degradation Test ---")

    # configure targets
    TARGET_NS = "vnode1"
    TARGET_IF = "veth1-2"

    # basic degradation
    apply_degradation(netns=TARGET_NS, interface=TARGET_IF, delay_ms=100, jitter_ms=20, loss_pct=10)
    
    print("[INFO] Testing active for 10 seconds...")
    time.sleep(10)

    # reset degradation back to baseline
    clear_degredation(netns=TARGET_NS, interface=TARGET_IF)
    print("--- Test Complete ---")